config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  post '/graphql', to: 'graphql#execute'

  # [STEALTH] No New Friends (or Users), but allow registered Users to edit themselves
  # https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password
  # (Solution 2)
  devise_for :users, skip: :registrations, controllers: {
    sessions: 'users/sessions'
  }
  as :user do
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    patch 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  root to: 'cards_app#index'

  resources :spend_categories
  resources :reward_currencies
  resources :banks
  resources :networks
  resources :cards
end

app/models/network.rb
class Network < ApplicationRecord
  has_many :cards

  validates_presence_of :name
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  before_action :set_network, only: [:show, :edit, :update, :destroy]

  # GET /networks
  def index
    @networks = Network.all
  end

  # GET /networks/1
  def show
  end

  # GET /networks/new
  def new
    @network = Network.new
  end

  # GET /networks/1/edit
  def edit
  end

  # POST /networks
  def create
    @network = Network.new(network_params)

    if @network.save
      redirect_to @network, notice: 'Network was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /networks/1
  def update
    if @network.update(network_params)
      redirect_to @network, notice: 'Network was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /networks/1
  def destroy
    @network.destroy
    redirect_to networks_url, notice: 'Network was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_network
      @network = Network.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def network_params
      params.require(:network).permit(:name)
    end
end

app/views/networks/_form.html.erb
<%= form_with(model: network, local: true) do |form| %>
  <% if network.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(network.errors.count, "error") %> prohibited this network from being saved:</h2>

      <ul>
      <% network.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :network_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/networks/edit.html.erb
<h1>Editing Network</h1>

<%= render 'form', network: @network %>

<%= link_to 'Show', @network %> |
<%= link_to 'Back', networks_path %>

app/views/networks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Networks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @networks.each do |network| %>
      <tr>
        <td><%= network.name %></td>
        <td><%= link_to 'Show', network %></td>
        <td><%= link_to 'Edit', edit_network_path(network) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Network', new_network_path %>

app/views/networks/new.html.erb
<h1>New Network</h1>

<%= render 'form', network: @network %>

<%= link_to 'Back', networks_path %>

app/views/networks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @network.name %>
</p>

<%= link_to 'Edit', edit_network_path(@network) %> |
<%= link_to 'Back', networks_path %>