config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  post '/graphql', to: 'graphql#execute'

  # [STEALTH] No New Friends (or Users), but allow registered Users to edit themselves
  # https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password
  # (Solution 2)
  devise_for :users, skip: :registrations, controllers: {
    sessions: 'users/sessions'
  }
  as :user do
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    patch 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  root to: 'cards_app#index'

  resources :spend_categories
  resources :reward_currencies
  resources :banks
  resources :networks
  resources :cards
end

app/models/reward_currency.rb
class RewardCurrency < ApplicationRecord
  validates_presence_of :name

  validates :value_cents, numericality: { greater_than_or_equal_to: 0.0 }
end

app/controllers/reward_currencies_controller.rb
class RewardCurrenciesController < ApplicationController
  before_action :set_reward_currency, only: [:show, :edit, :update, :destroy]

  # GET /reward_currencies
  def index
    @reward_currencies = RewardCurrency.all
  end

  # GET /reward_currencies/1
  def show
  end

  # GET /reward_currencies/new
  def new
    @reward_currency = RewardCurrency.new
  end

  # GET /reward_currencies/1/edit
  def edit
  end

  # POST /reward_currencies
  def create
    @reward_currency = RewardCurrency.new(reward_currency_params)

    if @reward_currency.save
      redirect_to @reward_currency, notice: 'Reward currency was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /reward_currencies/1
  def update
    if @reward_currency.update(reward_currency_params)
      redirect_to @reward_currency, notice: 'Reward currency was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /reward_currencies/1
  def destroy
    @reward_currency.destroy
    redirect_to reward_currencies_url, notice: 'Reward currency was successfully destroyed'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward_currency
      @reward_currency = RewardCurrency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reward_currency_params
      params.require(:reward_currency).permit(:name, :value_cents)
    end
end

app/views/reward_currencies/_form.html.erb
<%= form_with(model: reward_currency, local: true) do |form| %>
  <% if reward_currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reward_currency.errors.count, "error") %> prohibited this reward_currency from being saved:</h2>

      <ul>
      <% reward_currency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :reward_currency_name %>
  </div>

  <div class="field">
    <%= form.label :value_cents, 'Value (¢)' %>
    <%= form.text_field :value_cents, id: :reward_currency_value_cents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reward_currencies/edit.html.erb
<h1>Editing Reward Currency</h1>

<%= render 'form', reward_currency: @reward_currency %>

<%= link_to 'Show', @reward_currency %> |
<%= link_to 'Back', reward_currencies_path %>

app/views/reward_currencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reward Currencies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value (¢)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reward_currencies.each do |reward_currency| %>
      <tr>
        <td><%= reward_currency.name %></td>
        <td><%= reward_currency.value_cents %></td>
        <td><%= link_to 'Show', reward_currency %></td>
        <td><%= link_to 'Edit', edit_reward_currency_path(reward_currency) %></td>
        <td><%= link_to 'Destroy', reward_currency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reward Currency', new_reward_currency_path %>

app/views/reward_currencies/new.html.erb
<h1>New Reward Currency</h1>

<%= render 'form', reward_currency: @reward_currency %>

<%= link_to 'Back', reward_currencies_path %>

app/views/reward_currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reward_currency.name %>
</p>

<p>
  <strong>Value (¢):</strong>
  <%= @reward_currency.value_cents %>
</p>

<%= link_to 'Edit', edit_reward_currency_path(@reward_currency) %> |
<%= link_to 'Back', reward_currencies_path %>