config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  post '/graphql', to: 'graphql#execute'

  # [STEALTH] No New Friends (or Users), but allow registered Users to edit themselves
  # https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password
  # (Solution 2)
  devise_for :users, skip: :registrations, controllers: {
    sessions: 'users/sessions'
  }
  as :user do
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    patch 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  root to: 'cards_app#index'

  resources :spend_categories
  resources :reward_currencies
  resources :banks
  resources :networks
  resources :cards
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :bank, optional: true
  belongs_to :network

  has_many :rewards, dependent: :destroy

  accepts_nested_attributes_for :rewards, reject_if: :all_blank, allow_destroy: true

  monetize :annual_fee_cents, allow_nil: true

  validates_presence_of :name
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  def index
    @cards = Card.all
  end

  # GET /cards/1
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
    @card.rewards.build(percentage: 0.0)
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to @card, notice: 'Card was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /cards/1
  def update
    if @card.update(card_params)
      redirect_to @card, notice: 'Card was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /cards/1
  def destroy
    @card.destroy
    redirect_to cards_url, notice: 'Card was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name,
        :annual_fee,
        :network_id,
        :bank_id,
        rewards_attributes: [:percentage, :spend_category_id, :reward_currency_id, :id, :_destroy]
      )
    end
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Name*' %>
    <%= form.text_field :name, id: :card_name %>
  </div>

  <div class="field">
    <%= form.label :annual_fee, 'Annual Fee ($)' %>
    <%= form.number_field :annual_fee, id: :card_annual_fee, step: 0.01 %>
  </div>

  <div class="field">
    <%= form.label :network_id, 'Network*' %>
    <%= form.collection_select :network_id, Network.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :bank_id, 'Bank' %>
    <%= form.collection_select :bank_id, Bank.all, :id, :name, include_blank: '(None)' %>
  </div>

  <h4>Rewards</h4>

  <div id="rewards">
    <%= form.fields_for :rewards do |reward_fields| %>
      <%= render partial: 'reward_fields', locals: { f: reward_fields } %>
    <% end %>
  </div>

  <%= link_to_add_association 'Add Reward', form, :rewards, data: { association_insertion_node: '#rewards', association_insertion_method: 'append' } %>

  <div class="actions" style="margin-top: 40px;">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/_reward_fields.html.erb
<div class="fields fields--nested fields--rewards" style="margin: 20px 5px;">
  <%= f.label :percentage, 'Percent back* (0.00 - 100.00)' %>
  <%= f.number_field :percentage, step: 0.01 %>

  <%= f.label :spend_category_id, 'Spend Category*' %>
  <%= f.collection_select :spend_category_id, SpendCategory.all, :id, :name %>

  <%= f.label :reward_currency_id, 'Currency*' %>
  <%= f.collection_select :reward_currency_id, RewardCurrency.all, :id, :name %>

  <br/ >

  <%= link_to_remove_association 'Remove', f, wrapper_class: 'fields--rewards' %>
</div>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Annual fee</th>
      <th>Network</th>
      <th>Bank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.name %></td>
        <td><%= humanized_money_with_symbol(card.annual_fee) %></td>
        <td><%= card.network.name %></td>
        <td><%= card.bank.try(:name) %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>Annual fee:</strong>
  <%= humanized_money_with_symbol(@card.annual_fee) %>
</p>

<p>
  <strong>Network:</strong>
  <%= link_to @card.network.name, network_path(@card.network.id) %>
</p>

<% if @card.bank.present? %>
  <p>
    <strong>Bank:</strong>
    <%= link_to @card.bank.name, bank_path(@card.bank) %>
  </p>
<% end %>

<% if @card.rewards.present? %>
  <div>
    <h3>Rewards:</h3>

    <% @card.rewards.each do |reward| %>
      <p>
        <%= "#{reward.percentage}%" %>
        back on
        <%= reward.spend_category.try(:name) || 'everything' %>
        <strong>(<%= reward.reward_currency.name %>)</strong>
      </p>
    <% end %>
  </div>
<% end %>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>